---

- name: Odoo user
  ansible.builtin.user:
    name: "{{ odoo_user }}"
    uid: 10000
    shell: /bin/bash

- name: Add GeoIP ppa
  ansible.builtin.apt_repository:
      repo: "ppa:maxmind/ppa"
      state: present

- name: Remove packages that are stupid to have on a server
  ansible.builtin.apt:
    name:
      - snapd
      - whoopsie
    purge: true
    state: absent

- name: Load packages listen
  ansible.builtin.include_vars: packages.yml

- name: Install packages
  ansible.builtin.package:
    name: "{{ query('flattened', ['{{ deb_packages }}']) }}"
    state: present
    update_cache: yes

- name: Install npm packages
  ansible.builtin.npm:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    global: true
  with_items:
    "{{ npm_packages }}"

- name: Get geoIP database
  block:
    - name: Get geoIP database
      ansible.builtin.get_url:
        url: "https://git.io/GeoLite2-City.mmdb"
        dest: "/usr/share/GeoIP/"
        mode: '0644'
      become: true
  rescue:
    - name: Get geoIP database from alternative url
      ansible.builtin.get_url:
        url: "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb"
        dest: "/usr/share/GeoIP/"
        mode: '0644'
      become: true


